### PR TITLE
fix(oma-topics): atm state file not exist should create new

### PR DESCRIPTION
**Pull request by eatradish**

### CODE REVIEW

**Comment by eatradish** [comment]
LGTM

图片

**Comment by Cyanoxygen** [comment]
image
A new state file is created, however oma will keep trying to deserialize the empty file. Maybe creating this file with an empty array `[]` is better.

**Comment by Cyanoxygen** [comment]
image

With an empty JSON array in it oma no longer complains.

**Comment by MingcongBai** [comment]
> image
> 
> With an empty JSON array in it oma no longer complains.

It's probably better to do this, since the creation logic does not eliminate the warning until the first `oma topics` run.

**Review by MingcongBai — CHANGES_REQUESTED** [review]
See comments above.

**Review by Cyanoxygen — APPROVED** [review]

**Review by MingcongBai — APPROVED** [review]
LGTM (with state removed):

图片

**Comment by Cyanoxygen** [comment]
image

LGTM with expected behavior.

**Pull request merged**
